### PR TITLE
Add access tokens support

### PR DESCRIPTION
**Pull request by Sadzurami**
That move give more flexibility to manage trades even on limited accounts.

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
Very cool. I'd prefer to keep the option to use API keys and require opt-in to use access tokens, since this isn't an officially supported way of accessing the API.

**Comment by Sadzurami** [comment]
> Very cool. I'd prefer to keep the option to use API keys and require opt-in to use access tokens, since this isn't an officially supported way of accessing the API.

will be done

**Comment by Sadzurami** [comment]
> Very cool. I'd prefer to keep the option to use API keys and require opt-in to use access tokens, since this isn't an officially supported way of accessing the API.

Just to clarify. Maybe we should provide apikey to constructor or class property, instead of retrieving it?
In some cases that will be more useful, because steam required now 2fa to issue new key.

**Comment by Sadzurami** [comment]
> > Very cool. I'd prefer to keep the option to use API keys and require opt-in to use access tokens, since this isn't an officially supported way of accessing the API.
> 
> Just to clarify. Maybe we should provide apikey to constructor or class property, instead of retrieving it? In some cases that will be more useful, because steam required 2fa to issue new key now.

This looks better, yet. But for backward compatibility, better to not change this.

**Comment by Sadzurami** [comment]
> Very cool. I'd prefer to keep the option to use API keys and require opt-in to use access tokens, since this isn't an officially supported way of accessing the API.

I'm ready.

**Comment by DoctorMcKay** [comment]
How about we attempt to fetch an API key if it exists, and if it does then we use it.

If it doesn't exist, we use the access token and emit a warning that we're using an access token which isn't officially supported and may stop working at any time.

And we add a constructor option (something like `useAccessToken`) which uses the access token and doesn't emit any warnings.

**Comment by Sadzurami** [comment]
> How about we attempt to fetch an API key if it exists, and if it does then we use it.
> 
> If it doesn't exist, we use the access token and emit a warning that we're using an access token which isn't officially supported and may stop working at any time.
> 
> And we add a constructor option (something like `useAccessToken`) which uses the access token and doesn't emit any warnings.

Sound good. Will make it.

**Comment by Sadzurami** [comment]
Looks like i'm ready

**Comment by DoctorMcKay** [comment]
:+1: Looks good to me for now, thanks for this PR. I can't merge it right now but I should be able to merge and publish tomorrow or Monday at the latest.

**Pull request merged**
