### PR TITLE
Update storehouse-steamcommunity.js example

### PR DESCRIPTION
**Pull request by Aareksio**
This example should be updated as well.

Replaced email authenticator with 2FA token.

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
It's still a good idea to save the Steam Guard cookie.

**Comment by Aareksio** [comment]
It should be fine now.

Sorry for doing weired stuff with the issue, couldn't get IDE to keep indents on empty lines. In the end decided to edit online...

**Comment by DoctorMcKay** [comment]
You still need a 2FA code even if you have the Steam Guard cookie.

**Comment by Aareksio** [comment]
Steam Gurad cookie is saved and sent on login (with 2FA code).
What's the use of the cookie while using mobile authenticator?

**Comment by DoctorMcKay** [comment]
Your cookie needs to be a week old if you've only recently enabled the authenticator or else you can't trade. 

And nothing says that Valve won't require the cookie for something else in the future. It's just safest to keep it.

**Comment by Aareksio** [comment]
Never had a problem with the cookies, that's why I was confused. 
Anyway, it should be fine now, sends 2fa code every time, regardless of the cookie.

**Comment by DoctorMcKay** [comment]
:+1: Thanks!

**Pull request merged**
